### ISSUE TITLE
Merge usercase

### ISSUE THREAD

**Issue by salgo60** [wmde/wikidata-mismatch-finder#53]
Do we have a strategy/user case for handling merges in Wikidata ? I guess the "**statement_guid**" will "change"

Both Wikidata and example WikiTree ([Property:P2949](https://www.wikidata.org/wiki/Property:P2949)) are wikis --> objects are not persistant... 
* Example [merges done last week in Wikidata for objects connected to WikiTree  ](https://w.wiki/3nSG)

![image](https://user-images.githubusercontent.com/14206509/128594072-b2d6e2f6-a9b6-4759-80a9-0c3bf183c1cf.png)

**Comment by lydiapintscher** [comment]
I'll open a ticket for this in phabricator for later consideration.
